=== mef-dev/bpmn-examples/tmforum-apis/TMF724_Incident_Management/SuggestResolutionPrompt.schema.json
{
   "$schema":"http://json-schema.org/draft-07/schema#",
   "title":"SuggestResolutionPrompt",
   "type":"object",
   "properties":{
      "callType":{
         "type":"string",
         "description":"Prompt engineering strategy selector",
         "enum":[
            "OneShot",
            "ChainOfThought"
         ]
      },
      "apiOptions":{
         "type":"object",
         "description":"OpenAI connectivity options",
         "properties":{
            "url":{
               "type":"string",
               "description":"OpenAI endpoint URI starting from https"
            },
            "headers":{
               "type":"object",
               "properties":{
                  "Content-Type":{
                     "type":"string"
                  },
                  "Authorization":{
                     "type":"string"
                  }
               },
               "required":[
                  "Content-Type",
                  "Authorization"
               ]
            },
            "model":{
               "type":"string",
               "description":"A LLM model name to use",
               "enum":[
                  "llama3-70b",
                  "llama3-8b",
                  "codellama-7b-instruct",
                  "codellama-13b-instruct",
                  "codellama-34b-instruct",
                  "mixtral-8x22b-instruct",
                  "mixtral-8x7b-instruct",
                  "mistral-7b-instruct",
                  "mistral-7b",
                  "mixtral-8x22b",
                  "gemma-7b",
                  "gemma-2b",
                  "alpaca-7b",
                  "vicuna-7b",
                  "vicuna-13b",
                  "vicuna-13b-16k",
                  "falcon-7b-instruct",
                  "falcon-40b-instruct",
                  "openassistant-llama2-70b",
                  "open-mistral-7b",
                  "open-mistral-8x7b",
                  "open-mistral-8x22b",
                  "mistral-small-latest",
                  "mistral-medium-latest",
                  "omistral-large-latest",
                  "mistral-embed",
                  "codestral-latest",
                  "gpt-4-turbo",
                  "gpt-3.5-turbo",
                  "gpt-3.5-turbo-16k",
                  "code-davinci-002",
                  "code-cushman-001",
                  "text-embedding-ada-002",
                  "text-moderation-stable",
                  "text-moderation-latest"
               ]
            },
            "temperature":{
               "type":"number",
               "description":"Temperature is used to control the randomness of the output. When you set it higher, you'll get more random outputs. When you set it lower, towards 0, the values are more deterministic. A default value of 1 or 0.7 depending on the model you choose",
               "minimum":0,
               "maximum":2
            },
            "top_p":{
               "type":"number",
               "description":"The “top_p” value ranges from 0 to 2, where lower values increase determinism, and higher values increase randomness. When the top_p value is set to a lower value, the model will choose tokens from a smaller percentage of the highest probabilities",
               "minimum":0,
               "maximum":2
            },
            "frequency_penalty":{
               "type":"number",
               "description":"The frequency_penalty parameter allows you to control the model's tendency to generate repetitive responses. Higher values, like 1.0, encourage the model to explore more diverse and novel responses, while lower values, such as 0.2, make the model more likely to repeat information",
               "minimum":0,
               "maximum":2
            }
         },
         "required":[
            "url",
            "headers",
            "model"
         ]
      },
      "prompt":{
         "type":"string",
         "description":"A Prompt sentense, namely question what you would like to be answered by LLM"
      },
      "context":{
         "type":"string",
         "description":"A context is used by Retrieval-Augmented Generation (RAG) approach, an AI development technique where a large language model (LLM) is connected to an external knowledge base to improve the accuracy and quality of its responses. Types of sources that LLMs can connect to with RAG include document repositories, files, APIs, and databases"
      }
   },
   "required":[
      "callType",
      "apiOptions",
      "prompt"
   ]
}

=== mef-dev/bpmn-examples/tmforum-apis/TMF724_Incident_Management/SuggestResolutionPrompt.example.json
{
	"callType": "OneShot",
	"apiOptions": {
		"url": "https://api.mistral.ai/v1/chat/completions",
		"headers": {
			"Content-Type": "application/json",
			"Authorization": "Bearer VeQqahmjvTMFXvwxHoO4abzP1LOL7PjZ"
		},
		"model": "open-mistral-8x22b",
		"temperature": 0.1,
		"top_p": 1,
		"frequency_penalty": 1
	},
	"prompt": "router ping is not successfull",
	"context": "ETH_LINK_DOWN\r\nDescription\r\nThe network port connection is faulty. This alarm indicates that the Ethernet connection is incorrect and the port negotiation fails.\r\nAttribute\r\nAlarm ID\tAlarm Severity\tAlarm Type\r\n12793       Critical        Communications alarm\r\n\r\nParameters\r\nName\t        Meaning\r\nParameter 1     Indicates the chassis ID.\r\nParameter 2     Indicates the slot ID.\r\nParameter 3     Indicates the subcard ID.\r\nParameter 4     Indicates the port number.\r\nParameter 5     Indicates the port type.\r\nParameter 6     Indicates the port description.\r\nParameter 7     Indicates the interface type.\r\n                    0: UNI\r\n                    1: NNI\r\n                    2: FlexE interface\r\nImpact on the System\r\nCause 0:\r\n    The Ethernet ports on the local NE and remote NE work in different modes and fail to negotiate.\r\n    The link is faulty, the cable and optical fiber are incorrectly connected, or the remote device is faulty.\r\n    The working modes of the transmit and receive ports are inconsistent and the negotiation fails.\r\n\r\nCause 1: The transmission modes or the FEC modes of the connected ports are different.\r\n    The serveice maybe break.\r\n\r\nCause 2: When a router*s certified and non-certified 100GE 80 km optical modules are connected, the interconnection link fails due to different polarities.\r\n    The data transmission link fails.\r\n\r\nPossible Causes\r\nCause0:\r\n    The Ethernet ports on the local NE and remote NE work in different modes and fail to negotiate.\r\n    The link is faulty, the cable and optical fiber are incorrectly connected, or the remote device is faulty.\r\nCause1: The transmission modes or the FEC modes of the connected ports are different.\r\nCause2: When a router*s certified and non-certified 100GE 80 km optical modules are connected, the interconnection link fails due to different polarities.\r\n\r\nProcedure\r\nCause0:\r\n    The Ethernet ports on the local NE and remote NE work in different modes and fail to negotiate.\r\n        (1) On the NMS, check whether the Ethernet ports at both ends work in the same mode.\r\n        (2) If not, modify the configuration so that they work in the same mode. Then, check whether the alarm is cleared.\r\n\r\n    The link is faulty, the cable and optical fiber are incorrectly connected, or the remote device is faulty.\r\n        (1) Check whether the cable or optical fiber is faulty. If so, rectify the fault and check whether the alarm is cleared.\r\n        (2) If the alarm persists, check whether the remote device is faulty. Replace the board of the remote device and check whether the alarm is cleared.\r\n        (3) If the alarm persists, replace the board that reports the alarm and check whether the working mode of the optical port on the local device is the same as that of the optical port on the remote device. If the board is replaced and the working modes of the optical ports on the local and remote devices are the same, the alarm is automatically cleared.\r\n\r\nCause1: The transmission modes or the FEC modes of the connected ports are different.\r\n    Check whether the transmission modes or the FEC modes of the connected ports are the same. If not, locate the cause of the difference to make the transmission modes or the FEC modes of the connected ports be the same.\r\n\r\nCause2: When a router*s certified and non-certified 100GE 80 km optical modules are connected, the interconnection link fails due to different polarities.\r\n    On the NMS, enable SerDes polarity inversion for the 100GE or FlexE-100G interface.\r\n\r\nAlarm Correlation\r\nThe following alarms suppress the reporting of the current alarm: LSR_NO_FITED, ETH_LOS, LASER_MOD_ERR, LOOP_ALM\r\n"
}
